language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t codewhac/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true codewhac/react-test npm test

after_success:
  - docker build -t codewhac/multi-client ./client
  - docker build -t codewhac/multi-nginx ./nginx
  - docker build -t codewhac/multi-server ./server
  - docker build -t codewhac/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push codewhac/multi-client
  - docker push codewhac/multi-nginx 
  - docker push codewhac/multi-server
  - docker push codewhac/multi-worker